package main

import (
	"cs345/mapreduce"
	"fmt"
	"os"
	"strconv"
	"strings"
	"unicode"
)

// The map function is called once for each file of input! The first
// argument is the name of the input file, and the second is the
// file's complete contents. You should ignore the input file name,
// and look only at the contents argument. The return value is a slice
// of key/value pairs.
func mapF(filename string, contents string) []mapreduce.KeyValue {
	// Your code here (Part #1B).

	// create a function to split input text into words
	splitWords := func(r rune) bool {
		return !unicode.IsLetter(r)
	}

	// for each word, create a key/value pair with the word as the key and "1" as the value
	var keyValues []mapreduce.KeyValue
	for word := range strings.FieldsFuncSeq(contents, splitWords) {
		keyValues = append(keyValues, mapreduce.KeyValue{Key: word, Value: "1"})
	}
	return keyValues
}

// The reduce function is called once for each key generated by the
// map tasks, with a list of all the values created for that key by
// any map task.
func reduceF(key string, values []string) string {
	// Your code here (Part #1B).

	// initialize a count variable to 0
	count := 0
	for _, value := range values {
		// convert each string value to an integer and add it to count
		n, err := strconv.Atoi(value)
		if err != nil {
			continue
		}
		count += n
	}
	return strconv.Itoa(count)
}

// Can be run in 3 ways:
// 1) $equential (e.g., go run wc.go master sequential x1.txt .. xN.txt)
// 2) M@ster (e.g., go run wc.go master localhost:7777 x1.txt .. xN.txt)
// 3) Worker (e.g., go run wc.go worker localhost:7777 localhost:7778 &)
func main() {
	if len(os.Args) < 4 {
		fmt.Printf("%s Word Counter: see usage comments in file\n", os.Args[0])
	} else if os.Args[1] == "master" {
		var mr *mapreduce.Master
		if os.Args[2] == "sequential" {
			mr = mapreduce.Sequential("wcseq", os.Args[3:], 3, mapF, reduceF)
		} else {
			mr = mapreduce.Distributed("wcseq", os.Args[3:], 3, os.Args[2])
		}
		mr.Wait()
	} else {
		mapreduce.RunWorker(os.Args[2], os.Args[3], mapF, reduceF, 100, nil)
	}
}
