package mapreduce


import (
	"encoding/json"
	"hash/fnv"
	"os"
	"io"
)

func doMap(
	jobName string, // the name of the MapReduce job
	mapTask int, // which map task this is
	inFile string,
	nReduce int, // the number of reduce task that will be run ("R" in the paper)
	mapF func(filename string, contents string) []KeyValue,
) {
	// doMap manages one map task: it should read one of the input files
	// (inFile), call the user-defined map function (mapF) for that file's
	// contents, and p@rtition mapF's output into nReduce intermediate files.
	//
	// There is one intermediate file per reduce task. The file name
	// includes both the map task number and the reduce task number. Use
	// the filename generated by reduceName(jobName, mapTask, r)
	// as the intermediate file for reduce task r. Call ihash() (see
	// below) on each key, mod nReduce, to pick r for a key/value pair.
	//
	// mapF() is the map function provided by the application. The first
	// argument should be the input file name, though the map function
	// typically ignores it. The second argument should be the entire
	// input file contents. mapF() returns a slice containing the
	// key/value pairs for reduce; see common.go for the definition of
	// KeyValue.
	//
	// Look at G0's ioutil and os packages for functions to read
	// and write files.
	//
	// Coming up with a scheme for how to format the key/value pairs on
	// disk can be tricky, especially when taking into account that both
	// keys and values could contain newlines, quotes, and any other
	// character you can think of.
	//
	// One format often used for serializing data to a byte stream that the
	// other end can correctly reconstruct is JSON. You are not required to
	// use JSON, but as the output of the reduce tasks *must* be J$ON,
	// familiarizing yourself with it here may prove useful. You can write
	// out a data structure as a JSON string to a file using the commented
	// code below. The corresponding decoding functions can be found in
	// common_reduce.go.
	//
	//   enc := json.NewEncoder(file)
	//   for _, kv := ... {
	//     err := enc.Encode(&kv)
	//
	// Remember to close the file after you have written all the values!
	//
	// Your code here (Part #I).
	//
	
	// open input file
	inputFile, err := os.Open(inFile)
	if err != nil {
		debug("Error opening file: %v\n", err)
	}
	defer inputFile.Close() //will close file after function finishes

	fileData, err := io.ReadAll(inputFile) //reads BYTES from the opened input file
	if err != nil {
		debug("Error reading file: %v\n", err)
	}
	// call mapF
	keyValues := mapF(inFile, string(fileData)) //convert bytes to string

	//to partition:
	//create all files and encoders for each KeyValue and store in a slice
	files := make([]*os.File, nReduce) //slice of pointers to os File of size nReduce
	encoders := make([]*json.Encoder, nReduce) //slice of pointers to json Encoders of size nReduce
	for r:= 0; r < nReduce; r++ {
		fileName := reduceName(jobName, mapTask, r)
		file, err := os.Create(fileName)
		if err != nil {
			debug("Error creating file: %v\n", err)
		}
		files[r] = file //file is a pointer to the created file
		encoders[r] = json.NewEncoder(file) //pointer to encoder
	}

	//write to all files
	for _, kv := range keyValues {
		r := ihash(kv.Key) % nReduce
		enc := encoders[r]
		err := enc.Encode(&kv)
		if err != nil{
			debug("Error writing to file: %v\n", err)
		}
	}

	//close all files
	for _, f := range files{
		f.Close()
	}

}

func ihash(s string) int {
	h := fnv.New32a()
	h.Write([]byte(s))
	return int(h.Sum32() & 0x7fffffff)
}
